# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: singarde/matlas:1.0
    container_name: matlas
    command: --default-authentication-plugin=mysql_native_password
    restart: always
   
    ports:
      - 3307:3306

  